name: Cloud Foundry

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: cf-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  install-dk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/checkout@v5
      - run: npm add -D @sap/cds-dk
  deploy:
    uses: capire/samples/.github/workflows/cf.yaml@main
    secrets: inherit
    needs: [install-dk]
    with:
      environment: Staging
